variables:
  TF_TK_CREATION_ROOT: ${CI_PROJECT_DIR}/create_token
  TF_VM_CREATION_ROOT: ${CI_PROJECT_DIR}/create_vms
  TF_TK_VARS: -var=infisical_client_id=$INFISICAL_CID -var=infisical_client_secret=$INFISICAL_CS -var=infisical_workspace_id=$INFISICAL_PID
  TF_VM_VARS: -var=vsphere_user=$VSPHERE_USER -var=vsphere_pw=$VSPHERE_PASSWORD -var=infisical_client_id=$INFISICAL_CID -var=infisical_client_secret=$INFISICAL_CS -var=infisical_workspace_id=$INFISICAL_PID
  ANS_ROOT: ${CI_PROJECT_DIR}/ansible
  DOCKER_TF: hashicorp/terraform:1.10.5
  DOCKER_ALP: alpine/ansible:2.18.1

cache:
  # Only cache the .terraform folder across each job in this pipeline for the same commit
  key: ${CI_COMMIT_SHA}-vm
  paths:
    - create_vms/.terraform

stages:
  - terraform-tk-validate
  - terraform-tk-plan
  - terraform-tk-apply
  - terraform-vm-validate
  - terraform-vm-plan
  - terraform-vm-apply
  - terraform-vm-destroy



# [Requires $GENERATE_TOKEN] - This step validates the terraform files of the token creation process
terraform-tk-validate:
  stage: terraform-tk-validate
  image:
    name: $DOCKER_TF
    entrypoint: [""]
  script:
    - cd "${TF_TK_CREATION_ROOT}"
    - terraform init -input=false -reconfigure && terraform validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
      when: never
    - if: $CI_COMMIT_BRANCH && $GENERATE_TOKEN


# [Requires $GENERATE_TOKEN] - This step creates the plan of action to set up the tokens
terraform-tk-plan:
  stage: terraform-tk-plan
  image:
    name: $DOCKER_TF
    entrypoint: [""]
  before_script:
    - apk --no-cache add jq
    - alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
  script:
    - cd "${TF_TK_CREATION_ROOT}"
    - terraform init -input=false -reconfigure && terraform plan -input=false -out=plan.cache $TF_TK_VARS
  resource_group: default
  rules:
    - if: $DESTROY_ENABLED
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
      when: never
    - if: $CI_COMMIT_BRANCH && $GENERATE_TOKEN


# [Requires $GENERATE_TOKEN] - This step adds a manual pipeline step to deploy the tokens
terraform-tk-apply:
  stage: terraform-tk-apply
  image:
    name: $DOCKER_TF
    entrypoint: [""]
  dependencies:
  - terraform-tk-plan
  script:
    - cd "${TF_TK_CREATION_ROOT}"
    - terraform init -input=false -reconfigure && terraform apply $TF_TK_VARS -input=false
  resource_group: default
  rules:
    - if: $DESTROY_ENABLED
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $GENERATE_TOKEN
      when: manual

# This step validates the terraform files of the VM creation process
terraform-vm-validate:
  stage: terraform-vm-validate
  image:
    name: $DOCKER_TF
    entrypoint: [""]
  script:
    - cd "${TF_VM_CREATION_ROOT}"
    - terraform init -input=false -backend-config=password=${GITLAB_ACCESS_TOKEN} -reconfigure && terraform validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
      when: never
    - if: $GENERATE_TOKEN
      when: never
    - if: $CI_COMMIT_BRANCH


# This step creates the plan of action to set up the VMs
terraform-vm-plan:
  stage: terraform-vm-plan
  image:
    name: $DOCKER_TF
    entrypoint: [""]
  before_script:
    - apk --no-cache add jq
    - alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
  script:
    - cd "${TF_VM_CREATION_ROOT}"
    - terraform init -input=false -backend-config=password=${GITLAB_ACCESS_TOKEN} -reconfigure && terraform plan -input=false -out=plan.cache $TF_VM_VARS
    - terraform show --json plan.cache | convert_report > plan.json
  resource_group: default
  artifacts:
    paths:
      - ${TF_VM_CREATION_ROOT}/plan.cache
    reports:
      terraform: ${TF_VM_CREATION_ROOT}/plan.json
  rules:
    - if: $DESTROY_ENABLED
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
      when: never
    - if: $GENERATE_TOKEN
      when: never
    - if: $CI_COMMIT_BRANCH        # If there's no open merge request, add it to a *branch* pipeline instead.


# This step adds a manual pipeline step to deploy the VMs
terraform-vm-apply:
  stage: terraform-vm-apply
  image:
    name: $DOCKER_TF
    entrypoint: [""]
  dependencies:
  - terraform-vm-plan
  script:
    - cd "${TF_VM_CREATION_ROOT}"
    - terraform init -input=false -backend-config=password=${GITLAB_ACCESS_TOKEN} -reconfigure && terraform apply $TF_VM_VARS -input=false plan.cache
  resource_group: default
  rules:
    - if: $DESTROY_ENABLED
      when: never
    - if: $GENERATE_TOKEN
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual


# [Requires $DESTROY_ENABLED] - This step adds a manual pipeline step to destroy the deployed VMs
terraform-vm-destroy:
  stage: terraform-vm-destroy
  image:
    name: $DOCKER_TF
    entrypoint: [""]
  script:
    - cd "${TF_VM_CREATION_ROOT}"
    - terraform init -input=false -backend-config=password=${GITLAB_ACCESS_TOKEN} -reconfigure && terraform destroy $TF_VM_VARS -input=false -auto-approve
  resource_group: default
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DESTROY_ENABLED
      when: manual
